apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour
  namespace: tanzu-continuousdelivery-resources
spec:
  # Override Release name to avoid the pattern Namespace-Release
  # Ref: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.HelmRelease
  releaseName: contour
  targetNamespace: contour
  interval: 10m
  chart:
    spec:
      chart: contour
      version: 17.0.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: tanzu-continuousdelivery-resources

  # Ref: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.Install
  install:
    createNamespace: true
