variables: 
- name: resource_group
  value: tmc-bootstrap-automation
- name: storage_account
  value: tfstate01tmc
- name: service_connection
  value: warroyo-se-azure
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "cluster_yaml/*"
      - "terraform/*"
stages:
  - stage: validate
    jobs:
    - job: validate
      continueOnError: false
      steps:
      - task: TerraformInstaller@0
        displayName: "Install Terraform"
        inputs:
          terraformVersion: '1.5.4'
      - task: TerraformTaskv4@4
        displayName: 'init'
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: $(service_connection) # service connection created during setup
          backendAzureRmResourceGroupName: $(resource_group)
          backendAzureRmStorageAccountName: $(storage_account)
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'terraform.tfstate'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
      - task: TerraformTaskv4@4
        displayName: 'validate'
        inputs:
          provider: 'azurerm'
          command: 'validate'
          
  - stage: plan
    dependsOn: [validate]
    condition: succeeded('validate')
    jobs:
      - job: terraform_plan
        steps:
              - checkout: self
              - task: TerraformInstaller@0
                displayName: 'install'
                inputs:
                  terraformVersion: '1.5.4'
              - task: TerraformTaskv4@4
                displayName: 'init'
                inputs:
                  inputs:
                  provider: 'azurerm'
                  command: 'init'
                  backendServiceArm: $(service_connection)
                  backendAzureRmResourceGroupName: $(resource_group)
                  backendAzureRmStorageAccountName: $(storage_account)
                  backendAzureRmContainerName: 'tfstate'
                  backendAzureRmKey: 'terraform.tfstate'
                  workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
              - task: TerraformTaskv4@4
                displayName: 'plan'
                inputs:
                  provider: 'azurerm'
                  command: 'plan'
                  environmentServiceNameAzureRM: $(service_connection)
                  workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'

  - stage: apply
    dependsOn: [plan]
    condition: succeeded('plan')
    jobs:
      - job: terraform_apply
        steps:
              - checkout: self
              - task: TerraformInstaller@0
                displayName: 'install'
                inputs:
                  terraformVersion: '1.5.4'
              - task: TerraformTaskv4@4
                displayName: 'init'
                inputs:
                  inputs:
                  provider: 'azurerm'
                  command: 'init'
                  backendServiceArm: $(service_connection)
                  backendAzureRmResourceGroupName: $(resource_group)
                  backendAzureRmStorageAccountName: $(storage_account)
                  backendAzureRmContainerName: 'tfstate'
                  backendAzureRmKey: 'terraform.tfstate'
                  workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
              - task: TerraformTaskv4@4
                displayName: 'apply'
                inputs:
                  provider: 'azurerm'
                  command: 'apply'
                  environmentServiceNameAzureRM: $(service_connection)
                  workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
  - stage: template
    dependsOn: [apply]
    condition: succeeded('apply')
    jobs:
      - job: template_files
        steps:
            - checkout: self
            - task: UsePythonVersion@0
              inputs:
                versionSpec: '3.x' 
            - task: TerraformInstaller@0
              displayName: 'install'
              inputs:
                terraformVersion: '1.5.4'
            - task: TerraformTaskv4@4
              displayName: 'init'
              inputs:
                inputs:
                provider: 'azurerm'
                command: 'init'
                backendServiceArm: $(service_connection)
                backendAzureRmResourceGroupName: $(resource_group)
                backendAzureRmStorageAccountName: $(storage_account)
                backendAzureRmContainerName: 'tfstate'
                backendAzureRmKey: 'terraform.tfstate'
                workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
            - task: TerraformTaskv4@4
              displayName: 'output'
              inputs:
                provider: 'azurerm'
                command: 'output'
                outputTo: file
                outputFormat: json
                environmentServiceNameAzureRM: $(service_connection)
                workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
            - task: PythonScript@0
              inputs:
                scriptSource: 'filePath'
                scriptPath: '$(System.DefaultWorkingDirectory)/pipeline-scripts/generate-flux.yml'
                arguments:  $(output.jsonOutputVariablesPath)
                workingDirectory: '$(System.DefaultWorkingDirectory)/pipeline-scripts'
                failOnStderr: true # boolean. Fail on standard error. Default: false.