apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: tanzu-continuousdelivery-resources
spec:
  # Override Release name to avoid the pattern Namespace-Release
  # Ref: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.HelmRelease
  releaseName: cert-manager
  targetNamespace: cert-manager
  interval: 10m
  chart:
    spec:
      chart: cert-manager
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: tanzu-continuousdelivery-resources

  # Ref: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.Install
  install:
    createNamespace: true
