apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: tanzu-continuousdelivery-resources
spec:
  type: oci
  interval: 10m
  url: oci://registry-1.docker.io/bitnamicharts